apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: myapp-ui
  name: myapp-ui
  namespace: myapp
spec:
  containers:
    - image: krishnamaram2/myapp-ui:4fe4da70a1ff7d0fb573afd176ae557aebb56688
      name: myapp-ui
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
  restartPolicy: Always


apiVersion: v1
kind: Service
metadata:
  name: myapp-ui-svc
  namespace: myapp
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: myapp-ui
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30009
