apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ramupunuruorg/k8s-manifests.git       
    targetRevision: main    
    path: ingress
  destination:
    server: https://kubernetes.default.svc   
    namespace: myapp  
  syncPolicy:
  syncOptions:
      - CreateNamespace=true
  automated:
    prune: true
    selfHeal: true
