apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd # Namespace where ArgoCD will be installed
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080 # ArgoCD server's target port
  selector:
    app.kubernetes.io/name: argocd-server
