apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: myapp-ui
  name: myapp-ui
  namespace: myapp
spec:
  containers:
    - image: ramupunuru/angular-ui:34359a9fb453e822980d1dbf422890a18cdc828c
      name: myapp-ui
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
  restartPolicy: Always
