apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: myapp-ui
  name: myapp-ui
  namespace: myapp
spec:
  containers:
    - image: ramupunuru/angular-ui:64d054b448c213114f1037cf12a17055e7e99311
      name: myapp-ui
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
  restartPolicy: Always
