apiVersion: v1
kind: Service
metadata:
  name: myapp-ui-svc
  namespace: myapp
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: myapp-ui
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
