apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: myapp-ui
  name: myapp-ui
  namespace: myapp
spec:
  containers:
    - image: ramupunuru/angular-ui:55b8f4a64b8874b506fbd1579bbdf3f14ce454e1
      name: myapp-ui
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
  restartPolicy: Always
