apiVersion: v1
kind: Service
metadata:
  name: pythonapp-svc
  namespace: myapp
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: python-app
  ports:
    - port: 80
      targetPort: 5000
      # nodePort: 30009
