# comment
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: python-app
  name: python-app
  namespace: myapp
spec:
  containers:
    - image: ramupunuru/python-flask:26f788efc93f9de8767f80b03cf1370f572785ab
      name: python-app
      imagePullPolicy: Always
      ports:
        - containerPort: 5000
  restartPolicy: Always
