apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: python-app
  name: python-app
  namespace: pythonapp
spec:
  containers:
    - image: ramupunuru/python-flask:55b8f4a64b8874b506fbd1579bbdf3f14ce454e1
      name: python-app
      imagePullPolicy: Always
      ports:
        - containerPort: 5000
  restartPolicy: Always
