# comment
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: python-app
  name: python-app
  namespace: myapp
spec:
  containers:
    - image: ramupunuru/python-flask:b044a9067c4a080a0486113bc2531e5f133f3d37
      name: python-app
      imagePullPolicy: Always
      ports:
        - containerPort: 5000
  restartPolicy: Always
